-- liquibase formatted sql

-- changeset ARIEL:1 logicalFilePath:SET-UP.sql
CREATE TABLE PRODUCTS
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL
);

COMMENT ON TABLE PRODUCTS IS 'PRODUCTS';
COMMENT ON COLUMN PRODUCTS.ID IS 'ID';
COMMENT ON COLUMN PRODUCTS.NAME IS 'NAME';

-- changeset ARIEL:2 logicalFilePath:SET-UP.sql
CREATE TABLE BRANDS
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL
);

COMMENT ON TABLE BRANDS IS 'BRANDS';
COMMENT ON COLUMN BRANDS.ID IS 'ID';
COMMENT ON COLUMN BRANDS.NAME IS 'NAME';

-- changeset ARIEL:3 logicalFilePath:SET-UP.sql
CREATE TABLE PRICES
(
    ID                      INT PRIMARY KEY AUTO_INCREMENT,
    BRAND_ID           		INT,
    START_DATE		        TIMESTAMP,
    END_DATE	            TIMESTAMP,
    PRICE_LIST				INT NOT NULL,
    PRODUCT_ID				INT NOT NULL,
    PRIORITY				INT NOT NULL DEFAULT 0,
    PRICE					NUMBER(10, 2) NOT NULL DEFAULT 0,
    CURR					VARCHAR(3) NOT NULL DEFAULT 'EUR',
    CONSTRAINT PK_GRA_ID PRIMARY KEY (ID),
    CONSTRAINT FK_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(id) ON DELETE CASCADE,
    CONSTRAINT FK_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(id) ON DELETE CASCADE
);

COMMENT ON TABLE PRICES IS 'PRICES';
COMMENT ON COLUMN PRICES.ID IS 'ID';
COMMENT ON COLUMN PRICES.BRAND_ID IS 'FOREIGN KEY FOR BRANDS';
COMMENT ON COLUMN PRICES.START_DATE IS 'START DATE';
COMMENT ON COLUMN PRICES.END_DATE IS 'END DATE';
COMMENT ON COLUMN PRICES.PRICE_LIST IS 'PRICE LIST';
COMMENT ON COLUMN PRICES.PRODUCT_ID IS 'FOREIGN KEY FOR PRODUCTS';
COMMENT ON COLUMN PRICES.PRIORITY IS 'PRIORITY';
COMMENT ON COLUMN PRICES.PRICE IS 'PRICE';
COMMENT ON COLUMN PRICES.CURR IS 'CURRENCY';